package com.colpencil.redwood.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEARCH_HISTORY.
 */
public class SearchHistory {

    private Long id;
    private String history;
    private Integer cat_id;

    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    public SearchHistory(Long id, String history, Integer cat_id) {
        this.id = id;
        this.history = history;
        this.cat_id = cat_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHistory() {
        return history;
    }

    public void setHistory(String history) {
        this.history = history;
    }

    public Integer getCat_id() {
        return cat_id;
    }

    public void setCat_id(Integer cat_id) {
        this.cat_id = cat_id;
    }

}
