package com.colpencil.redwood.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table SORT_VO.
*/
public class SortVoDao extends AbstractDao<SortVo, Long> {

    public static final String TABLENAME = "SORT_VO";

    /**
     * Properties of entity SortVo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cat_name = new Property(1, String.class, "cat_name", false, "CAT_NAME");
        public final static Property Cat_id = new Property(2, String.class, "cat_id", false, "CAT_ID");
    };


    public SortVoDao(DaoConfig config) {
        super(config);
    }

    public SortVoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SORT_VO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CAT_NAME' TEXT," + // 1: cat_name
                "'CAT_ID' TEXT);"); // 2: cat_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SORT_VO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SortVo entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String cat_name = entity.getCat_name();
        if (cat_name != null) {
            stmt.bindString(2, cat_name);
        }

        String cat_id = entity.getCat_id();
        if (cat_id != null) {
            stmt.bindString(3, cat_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public SortVo readEntity(Cursor cursor, int offset) {
        SortVo entity = new SortVo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cat_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // cat_id
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SortVo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCat_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCat_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SortVo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(SortVo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
