package com.colpencil.redwood.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SORT_VO.
 */
public class SortVo {

    private Long id;
    private String cat_name;
    private String cat_id;

    public SortVo() {
    }

    public SortVo(Long id) {
        this.id = id;
    }

    public SortVo(Long id, String cat_name, String cat_id) {
        this.id = id;
        this.cat_name = cat_name;
        this.cat_id = cat_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCat_name() {
        return cat_name;
    }

    public void setCat_name(String cat_name) {
        this.cat_name = cat_name;
    }

    public String getCat_id() {
        return cat_id;
    }

    public void setCat_id(String cat_id) {
        this.cat_id = cat_id;
    }

}
